apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontappName }}
  labels:
    {{- include "homework5.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.frontappLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.frontappLabels | nindent 4 }}