apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backappName }}
  labels:
    {{- include "homework5.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.backappLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backappPort }}
      targetPort: {{ .Values.backappPort }}
  selector:
    {{- toYaml .Values.backappLabels | nindent 4 }}
